db.movies.insert({Movie_name:"The Godfather",IMDB_Rating:9.2,Genre:"Crime",No_of_feedback:100,Referable:"True"})
db.movies.insert({Movie_name:"The Dark Night",IMDB_Rating:9.0,Genre:"Action",No_of_feedback:82,Referable:"True"})
db.movies.insert({Movie_name:"12 Angry Men",IMDB_Rating:9.0,Genre:"Crime",No_of_feedback:96,Referable:"True"})
db.movies.insert({Movie_name:"Interstellar",IMDB_Rating:8.6,Genre:"Sci-fi",No_of_feedback:74,Referable:"True"})
db.movies.insert({Movie_name:"The Hungover Games",IMDB_Rating:3.5,Genre:"Comedy",No_of_feedback:15,Referable:"False"})
db.movies.insert({Movie_name:"The Fog",IMDB_Rating:3.8,Genre:"Horror",No_of_feedback:20,Referable:"False"})
db.movies.insert({Movie_name:"Separation",IMDB_Rating:4.5,Genre:"Horror",No_of_feedback:47,Referable:"False"})
db.movies.insert({Movie_name:"Taxi",IMDB_Rating:4.5,Genre:"Crime",No_of_feedback:27,Referable:"True"})
db.movies.insert({Movie_name:"The Unholy",IMDB_Rating:5.0,Genre:"Thriller",No_of_feedback:36,Referable:"True"})
db.movies.insert({Movie_name:"The Happening",IMDB_Rating:5.0,Genre:"Sci-fi",No_of_feedback:67,Referable:"False"})
db.movies.insert({Movie_name:"After Life",IMDB_Rating:5.9,Genre:"Thriller",No_of_feedback:48,Referable:"False"})
db.movies.insert({Movie_name:"Big Daddy",IMDB_Rating:6.4,Genre:"Comedy",No_of_feedback:41,Referable:"True"})
db.movies.insert({Movie_name:"Bolt",IMDB_Rating:6.8,Genre:"Comedy",No_of_feedback:"",Referable:"True"})
db.movies.insert({Movie_name:"Sherlock Holmes",IMDB_Rating:7.6,Genre:"Action",No_of_feedback:57,Referable:"True"})
db.movies.insert({Movie_name:"Moonrise",IMDB_Rating:7.8,Genre:"Comedy",No_of_feedback:84,Referable:"False"})
db.movies.insert({Movie_name:"Magnolia",IMDB_Rating:8.0,Genre:"Thriller",No_of_feedback:77,Referable:"False"})
db.movies.insert({Movie_name:"Before Midnight",IMDB_Rating:7.9,Genre:"Thriller",No_of_feedback:94,Referable:"False"})
db.movies.insert({Movie_name:"The Raid 2",IMDB_Rating:8.0,Genre:"Crime",No_of_feedback:73,Referable:"True"})
db.movies.insert({Movie_name:"The Room",IMDB_Rating:3.7,Genre:"Horror",No_of_feedback:34,Referable:"True"})
db.movies.insert({Movie_name:"The Wicker Man",IMDB_Rating:3.7,Genre:"Horror",No_of_feedback:26,Referable:"False"})
